name: CI
on: [push]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: workarea-commerce/ci/rubocop@ruby-2.4
      env:
        BUNDLE_GEMS__WEBLINC__COM: ${{ secrets.BUNDLE_GEMS__WEBLINC__COM }}
        GITHUB_TOKEN: ${{ secrets.github_access_token }}
  bundler_audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: workarea-commerce/ci/bundler-audit@ruby-2.4
      env:
        BUNDLE_GEMS__WEBLINC__COM: ${{ secrets.BUNDLE_GEMS__WEBLINC__COM }}
        GITHUB_TOKEN: ${{ secrets.github_access_token }}
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: workarea-commerce/ci/eslint@v1
      with:
        args: '**/*.js'
  stylelint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: workarea-commerce/ci/stylelint@v1
      with:
        args: '**/*.scss'

  admin_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: bin/rails app:workarea:test:admin
      env:
        BUNDLE_GEMS__WEBLINC__COM: ${{ secrets.BUNDLE_GEMS__WEBLINC__COM }}
        GITHUB_TOKEN: ${{ secrets.github_access_token }}

  core_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: bin/rails app:workarea:test:core
      env:
        BUNDLE_GEMS__WEBLINC__COM: ${{ secrets.BUNDLE_GEMS__WEBLINC__COM }}
        GITHUB_TOKEN: ${{ secrets.github_access_token }}

  storefront_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: bin/rails app:workarea:test:storefront
      env:
        BUNDLE_GEMS__WEBLINC__COM: ${{ secrets.BUNDLE_GEMS__WEBLINC__COM }}
        GITHUB_TOKEN: ${{ secrets.github_access_token }}

  plugins_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: bin/rails app:workarea:test:plugins
      env:
        BUNDLE_GEMS__WEBLINC__COM: ${{ secrets.BUNDLE_GEMS__WEBLINC__COM }}
        GITHUB_TOKEN: ${{ secrets.github_access_token }}

teaspoon:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v1
  - uses: actions/setup-ruby@v1
    with:
      ruby-version: 2.6.x
  - uses: workarea-commerce/ci/test@v1
    with:
      command: bin/rails app:teaspoon
